export const TOGGLE_IS_DARK_MODE = "TOGGLE_IS_DARK_MODE";
export const TOGGLE_IS_CELSIUS = "TOGGLE_IS_CELSIUS";
export const SELECT_LOCATION_KEY = "SELECT_LOCATION_KEY";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";